---
# This playbook is for setting up elastic stack
# You can run this playbook with the following command:
# sudo ansible-playbook -i hosts/elastic.hosts playbooks/elk_setup.yml

- hosts: elk_stack
  connection: local
  remote_user: root
  become: true
  roles:
     - role: java8
     - role: elastic_stack
     - role: logstash
     - role: elasticsearch
     - role: kibana
