---
# This playbook is for setting up filebeat
# You can run this playbook with the following command:
# sudo ansible-playbook -i hosts/elastic.hosts playbooks/filebeat.yml

- hosts: filebeat
  connection: local
  remote_user: root
  become: true
  roles:
#    - role: elastic_stack
#    - role: filebeat
  tasks:
    # If you're using filebeat installed on another server(s), you need to load the filebeat template
    - name: Load Filebeat template
      uri:
        url: http://localhost:9200/_template/filebeat-6.3.1
        method: PUT
        headers:
          Content-Type: "application/json"
        body: "{{ lookup('file','/tmp/filebeat.template.json') }}"
        body_format: json
